# generated by datamodel-codegen:
#   filename:  cloudEvent_alerta_processed.schema.json
#   timestamp: 2025-12-12T15:27:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import Field

from .alert_raw import Schema as Schema_1


class PreviousSeverity(Enum):
    security = 'security'
    critical = 'critical'
    major = 'major'
    minor = 'minor'
    warning = 'warning'
    informational = 'informational'
    debug = 'debug'
    trace = 'trace'
    indeterminate = 'indeterminate'
    cleared = 'cleared'
    normal = 'normal'
    ok = 'ok'
    unknown = 'unknown'


class TrendIndication(Enum):
    moreSevere = 'moreSevere'
    lessSevere = 'lessSevere'
    noChange = 'noChange'


class Schema(Schema_1):
    id: Optional[str] = Field(None, description='globally unique random UUID')
    customer: Optional[Any] = Field(
        None,
        description="assigned based on the owner of the API key used when submitting the alert, if 'Customer Views' is enabled, or can be set if admin user",
    )
    duplicateCount: Optional[float] = Field(
        None,
        description='a count of the number of times this event has been received for a resource',
    )
    repeat: Optional[bool] = Field(
        None,
        description='if duplicateCount is 0 or the alert status has changed then repeat is False, otherwise it is True',
    )
    previousSeverity: Optional[PreviousSeverity] = Field(
        None,
        description='the previous severity of the same event for this resource. if no event or correlate events exist in the database for this resource then it will be unknown',
    )
    trendIndication: Optional[TrendIndication] = Field(
        None,
        description='based on severity and previousSeverity will be one of moreSevere, lessSevere or noChange',
    )
    receiveTime: Optional[Any] = Field(
        None,
        description='UTC datetime the alert was received by the Alerta server daemon',
    )
    lastReceiveId: Optional[str] = Field(
        None,
        description='the last time this alert was received. only different to receiveTime if the alert is a duplicate',
    )
    updateTime: Optional[Any] = Field(
        None,
        description='the last time the alert status changed. used to calculate time remaining until an alert times out',
    )
    history: Optional[List] = Field(
        None,
        description='whenever an alert changes severity or status then a list of key alert attributes are appended to the history log',
    )
