# generated by datamodel-codegen:
#   filename:  cloudEvent_alerta_raw.schema.json
#   timestamp: 2025-11-05T13:50:41+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field


class Environment(Enum):
    Development = 'Development'
    Production = 'Production'


class Severity(Enum):
    security = 'security'
    critical = 'critical'
    major = 'major'
    minor = 'minor'
    warning = 'warning'
    informational = 'informational'
    debug = 'debug'
    trace = 'trace'
    indeterminate = 'indeterminate'
    cleared = 'cleared'
    normal = 'normal'
    ok = 'ok'
    unknown = 'unknown'


class Status(Enum):
    open = 'open'
    assign = 'assign'
    ack = 'ack'
    closed = 'closed'
    expired = 'expired'
    blackout = 'blackout'
    shelved = 'shelved'
    unknown = 'unknown'


class AlertCategory(Enum):
    Operations_alerts = 'Operations alerts'
    Data_management = 'Data management'
    Information = 'Information'
    Support_requests = 'Support requests'
    EEZ = 'EEZ'
    Beaching = 'Beaching'
    Icing = 'Icing'
    Technical_issue = 'Technical issue'
    Battery_issue = 'Battery issue'
    Data_checker = 'Data checker'
    QC_feedback = 'QC feedback'
    Metadata_check = 'Metadata check'
    Platform = 'Platform'
    Cruises = 'Cruises'
    Data = 'Data'
    New_platform = 'New platform'
    Platform_recovery = 'Platform recovery'
    New_Cruises = 'New Cruises'
    New_data_flow = 'New data flow'
    Deployment_Retrieval = 'Deployment or Retrieval'
    Deployment_request = 'Deployment request'
    Retrieval_request = 'Retrieval request'
    Data_processing_request = 'Data processing request'
    Data_access_request = 'Data access request'
    Dashboard = 'Dashboard'


class MqttTopic(Enum):
    operations_alerts = 'operations-alerts'
    data_management = 'data-management'
    information = 'information'
    support_requests = 'support-requests'


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    Country: str = Field(..., description='country of origin of the alert')
    lastCycleNumberToRaiseAlarm: Optional[str] = Field(
        None, description='Float last cycle number which raised the alert'
    )
    LastStationDate: Optional[Any] = Field(
        None, description='Float last station UTC date-time'
    )
    basin_id: Optional[str] = Field(None, description='Identification of maritime zone')
    wigos_id: Optional[str] = Field(None, description='WIGOS Station Identifiers')
    url: Optional[str] = Field(
        None, description='URL for more informations on the resource'
    )
    dac_name: Optional[str] = Field(
        None,
        description='name of the dac managing the resource responsible of the alert',
    )
    alert_category: AlertCategory = Field(..., description='category of alert. See XXX')
    mqtt_topic: Optional[MqttTopic] = Field(
        None, description='MQTT topic on which the alert was received'
    )


class Schema(BaseModel):
    resource: str = Field(..., description='Unique identifier of resource under alarm.')
    event: str = Field(..., description='event name')
    environment: Environment = Field(
        ...,
        description='Environment, used to namespace the resource. Development or Production.',
    )
    severity: Optional[Severity] = Field(
        None, description='Severity of alert (default normal)'
    )
    correlate: Optional[List[str]] = None
    status: Optional[Status] = Field(None, description='Status of alert (default open)')
    service: Set[str] = Field(
        ..., description='list of effected services', min_length=1
    )
    group: Optional[str] = Field(
        None, description='event group used to group events of similar type'
    )
    value: Optional[str] = Field(
        None, description='event value eg. 100%, Down, PingFail, 55ms, ORA-1664'
    )
    text: Optional[str] = Field(None, description='freeform text description')
    tags: Optional[Set[str]] = Field(
        None,
        description='set of tags in any format eg. aTag, aDouble:Tag, a:Triple=Tag',
    )
    attributes: Optional[Attributes] = Field(
        None, description='Dictionary of key-value pairs'
    )
    origin: Optional[str] = Field(
        None, description='name of monitoring component that generated the alert'
    )
    type: Optional[str] = Field(
        None, description='alert type eg. snmptrapAlert, syslogAlert, gangliaAlert'
    )
    createTime: Optional[Any] = Field(
        None, description='UTC date-time the alert was generated in ISO8601 format'
    )
    timeout: Optional[int] = Field(
        None, description='number of seconds before alert is considered stale'
    )
    rawData: Optional[str] = Field(
        None, description='unprocessed data eg. full syslog message or SNMP trap'
    )
