COLUMNS = ['resource','severity',  'status','event','value','text','Country', 'FleetMonitoringLink', 'lastReceiveTime','lastCycleNumberToRaiseAlarm']

# VERIFY_JWT_JWKS_ENDPOINT='http://172.21.144.1:3000/api/oceanops/auth/.well-known/jwks.json'





