# generated by datamodel-codegen:
#   filename:  cloudEvent_alerta_raw.schema.json
#   timestamp: 2025-12-12T15:27:09+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, BaseModel, Field, RootModel, constr

from . import Alert_raw


class Iddef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Sourcedef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Specversiondef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Typedef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Datacontenttypedef(RootModel[Optional[constr(min_length=1)]]):
    root: Optional[constr(min_length=1)]


class Dataschemadef(RootModel[Optional[AnyUrl]]):
    root: Optional[AnyUrl]


class Subjectdef(RootModel[Optional[constr(min_length=1)]]):
    root: Optional[constr(min_length=1)]


class Timedef(RootModel[Optional[datetime]]):
    root: Optional[datetime]


class Datadef(RootModel[Optional[Union[Dict[str, Any], str, float, List[Any], bool]]]):
    root: Optional[Union[Dict[str, Any], str, float, List[Any], bool]]


class DataBase64def(RootModel[Optional[str]]):
    root: Optional[str]


class CloudEventAlertaRaw(BaseModel):
    id: Iddef = Field(
        ..., description='Identifies the event.', examples=['A234-1234-1234']
    )
    source: Sourcedef = Field(
        ...,
        description='Identifies the context in which an event happened.',
        examples=[
            'https://github.com/cloudevents',
            'mailto:cncf-wg-serverless@lists.cncf.io',
            'urn:uuid:6e8bc430-9c3a-11d9-9669-0800200c9a66',
            'cloudevents/spec/pull/123',
            '/sensors/tn-1234567/alerts',
            '1-555-123-4567',
        ],
    )
    specversion: Specversiondef = Field(
        ...,
        description='The version of the CloudEvents specification which the event uses.',
        examples=['1.0'],
    )
    type: Typedef = Field(
        ...,
        description='Describes the type of event related to the originating occurrence.',
        examples=['com.github.pull_request.opened', 'com.example.object.deleted.v2'],
    )
    datacontenttype: Optional[Datacontenttypedef] = Field(
        None,
        description='Content type of the data value. Must adhere to RFC 2046 format.',
        examples=['text/xml', 'application/json', 'image/png', 'multipart/form-data'],
    )
    dataschema: Optional[Dataschemadef] = Field(
        None, description='Identifies the schema that data adheres to.'
    )
    subject: Optional[Subjectdef] = Field(
        None,
        description='Describes the subject of the event in the context of the event producer (identified by source).',
        examples=['mynewfile.jpg'],
    )
    time: Optional[Timedef] = Field(
        None,
        description='Timestamp of when the occurrence happened. Must adhere to RFC 3339.',
        examples=['2018-04-05T17:31:00Z'],
    )
    data: Alert_raw.Schema = Field(..., description='The event payload.')
    data_base64: Optional[DataBase64def] = Field(
        None,
        description='Base64 encoded event payload. Must adhere to RFC4648.',
        examples=['Zm9vYg=='],
    )
