"""
Utility functions for building CloudEvent and Alert payloads.
"""

from datetime import datetime, timezone
from typing import Any, List
import uuid
from amrit_mqtt_publisher.models import Alert_raw, CloudEventAlertaRaw


def cloud_event_builder(
    alert: Alert_raw.Schema,
) -> CloudEventAlertaRaw:
    """
    Build a CloudEventAlertaRaw object from an alert payload.

    Parameters
    ----------
    alert : Alert_raw.Schema
        The alert payload (already validated).
    source : str
        The logical event source (e.g., "amrit-system").
    event_type : str
        CloudEvent type string (e.g., "amrit.alert.generated").
    subject : str | None
        Optional subject (e.g., float ID).

    Returns
    -------
    CloudEventAlertaRaw
        A fully valid CloudEvent with autogenerated ID and timestamp.
    """
    return CloudEventAlertaRaw(
        id=str(uuid.uuid4()),
        source=alert.origin or 'Unknown',
        specversion="1.0",
        type="amrit alert",
        datacontenttype="application/json",
        subject=alert.resource,
        time=datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
        data=alert,
    ) # type: ignore